### ISSUE TITLE
Can't activate slider

### ISSUE THREAD

**Issue by Crazy2BU** [Energeticthemes/neat-slider#2]
Greetings - I discovered the neat-slider and love the demo. I installed the slider on my Wordpress 4.2.2 site and attempted to activate it. I received the following fail:
Parse error: syntax error, unexpected T_FUNCTION in /home/content/d/a/n/dantac/html/lightsourcearts/wp-content/plugins/neat-slider/neat-slider.php on line 115

Your help resolving the issue would be wonderful as I find your slider to be superlative to others.

Best regards,

Dan at Lightsource Arts

**Comment by Energeticthemes** [comment]
Hi, Dan at Lightsource Arts

Line 110 uses a PHP anonymous function, which were introduced in PHP 5.3.
This means that your hosting server is using a very old version of PHP.
Neat-slider plugin requires PHP 5.3 or newer.
No worry ask to your host to upgrade PHP version PHP 5.3 or newer i am sure
they will do instantly.
If you face any trouble feel free to ask me i am here to help you.
Thanks Dan at Lightsource Arts.
Regards

**Comment by Crazy2BU** [comment]
Thanks for the tip. I contacted my host and they are upgrading my site.

Love the look of your plugin. Hopefully, I will be up and running soon.

Best regards,

Dan at Lightsource Arts
