### ISSUE TITLE
Spinning & Spinning

### ISSUE THREAD

**Issue by Crazy2BU** [Energeticthemes/neat-slider#4]
Greetings:
I had a previous problem activating your plugin which was resolved with my host updating my PHP to 5.3.
Now, however, after activating your plug-in and adding a few images, I attempted to preview the slider. The page opens, but there is a spinning wheel where the slider should be...and spins, and spins, and... You get the idea, no slider. Just a spinning wheel.

Your slider looks really cool, but it is not working as I hoped. Perhaps you can shed some light on my problem.

Best regards,

Dan at Lightsource Arts

**Comment by Crazy2BU** [comment]
Guys - Are you planning to respond to the issue I described above? Need a direction from you.

Best regards,

Dan at Lightsource Arts

**Comment by Energeticthemes** [comment]
Its due to query conflict mode no worry i fix it and update it. 
Thanks

**Comment by Crazy2BU** [comment]
I appreciate your effort.

Thx.

**Comment by Crazy2BU** [comment]
Any idea how long your update will take. Just asking so I know if I should wait.

Thanks.

**Comment by Energeticthemes** [comment]
New update is available on WordPress.org its will be update soon here.

Thanks

**Comment by Crazy2BU** [comment]
Very good. I updated your plugin and it works!

Thank you!!
